[module]
id = "std"
name = "Complogic Gates"

[[gates]]
id = "and"
name = "And Gate"
description = "A gate that performs a logical AND operation on two inputs."
inputs = 2
outputs = 1

[[gates]]
id = "counter"
name = "Counter"
description = "A gate that increments an internal counter."
inputs = 0
outputs = 1
