[module]
id = "std"
name = "Complogic Gates"
src = "target/wasm32-unknown-unknown/debug/complogic_gates.wasm"

[[gates]]
id = "and"
name = "And Gate"
description = "A gate that performs a logical AND operation on two inputs."
inputs = 2
outputs = 1

[[gates]]
id = "counter"
name = "Counter"
description = "A gate that increments an internal counter."
inputs = 0
outputs = 32

[[gates]]
id = "identity"
name = "Identity Gate"
description = "A gate that outputs the same value as its input."
inputs = 32
outputs = 32
